version: '3.5'

services:
  app: 
    image: node:20-alpine
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 5173:5173
    command: yarn dev --host 0.0.0.0
    tty: true